### ISSUE TITLE
How should I set /examples/exampleSettings/Params.yaml to use all filters？

### ISSUE THREAD

**Issue by guangzhaohui** [Radiomics/pyradiomics#367]
Hi everyone!
Since I am about to begin a radiomic study ex novo, I just wanted to extract images with all filters.  
Now
How should I set /examples/exampleSettings/Params.yaml？

# Settings to use, possible settings are listed in the documentation (section "Customizing the extraction").
setting:
  binWidth: 25
  label: 1
  interpolator: 'sitkBSpline' # This is an enumerated value, here None is not allowed
  resampledPixelSpacing: # This disables resampling, as it is interpreted as None, to enable it, specify spacing in x, y, z as [x, y , z]
  weightingNorm: # If no value is specified, it is interpreted as None

# Image types to use: "Original" for unfiltered image, for possible filters, see documentation.
imageType:
  Original: {} # for dictionaries / mappings, None values are not allowed, '{}' is interpreted as an empty dictionary
   LoG: {'sigma' : [1.0,2.0,3.0,4.0,5.0]} 
   Wavelet:
   Square: 
   SquareRoot:
   Logarithm: 
   Exponential: 

Thank you very much in advance,
Guangzhaohui

**Comment by JoostJM** [comment]
There is no way to specify "all filters", but the are all listed in the documentation and you can enable them all by specifying the in your parameter file as follows:

```
imageType:
  Original: {}  # no custom settings
  LoG: {sigma: (0.5, 1.0, 2.0)}  # custom settings defined in-line
  Wavelet: {}
  LBP3D:
    binWidth: 1.0  # Customized settings defined in tree-structure
  (...)  # add the other filters here
```

The name (case-sensitive) of the filter is specified by the function name implementing that filter:
`get<Filter>Image()`, e.g. `getLoGImage` is enabled by specifying `LoG`. All filters are implemented [here](http://pyradiomics.readthedocs.io/en/latest/radiomics.html#radiomics.imageoperations.getOriginalImage).

N.B. For local binary pattern there are separate implementations for 2D and 3D, so ensure you have the one that matches you extraction type.
