### ISSUE TITLE
Voxelwise featuremap misalignment

### ISSUE THREAD

**Issue by nwschurink** [Radiomics/pyradiomics#472]
When performing voxelwise feature extraction, the resulting featuremap has an offset compared to the original input mask.

I've used following parameter file
```
imageType:
  Original: {}

featureClass:
  firstorder: ['entropy']

setting:
  binWidth: 0.1
  force2D: false
  label: 1
  normalize: true
  verbose: true

voxelSetting:
  kernelRadius: 3
  maskedKernel: False
  initValue: nan
  voxelBatch: 10000
```

and following code

```
extractor = featureextractor.RadiomicsFeaturesExtractor(parameters)
result = extractor.execute(T2_image,T2_mask,voxelBased=True)
sitk.WriteImage(result['original_firstorder_Entropy'],'entropy_map.nii.gz')
```

The result looks like a correct feature map, however when loading in 3DSlicer the feature map and original mask don't line up

![image](https://user-images.githubusercontent.com/12720130/53815032-219fa900-3f61-11e9-9779-579b93ba2750.png)
![image](https://user-images.githubusercontent.com/12720130/53815050-2b291100-3f61-11e9-8414-645f70291248.png)
![image](https://user-images.githubusercontent.com/12720130/53815067-311ef200-3f61-11e9-879b-da004c492aaf.png)

direction cosines and pixelspacing are the same (up to a very small offset)
```
In[8]: result.GetDirection()
Out[8]: 
(0.9998692168806838,
 -0.0017433978040942717,
 0.01607823644291258,
 -0.002462451867338953,
 -0.998992429138316,
 0.04481141261257783,
 -0.015983912700255,
 0.04484514565059839,
 0.9988660709086836)

In[9]: T2_mask.GetDirection()
Out[9]: 
(0.9998692168806839,
 -0.0017433978040942736,
 0.01607823644291257,
 -0.002462451867338953,
 -0.9989924291383161,
 0.04481141261257781,
 -0.01598391270025502,
 0.04484514565059839,
 0.9988660709086835)

In [12]: foo.GetSpacing()
Out[12]: (0.78125, 0.78125, 5.000000953674316)

In [13]: T2_mask.GetSpacing()
Out[13]: (0.7812500000000004, 0.7812499999999999, 5.0000009536743235)
```
I figured out the exact translation between the output feature map and input mask and this is  [0.78125, -0.78125, 5.00], which shows that the mask is exactly 1 pixel off in each direction.

![image](https://user-images.githubusercontent.com/12720130/53816189-6f1d1580-3f63-11e9-93f6-0f89c14002cd.png)

![image](https://user-images.githubusercontent.com/12720130/53816255-907e0180-3f63-11e9-954d-da7c403ce85b.png)

Maybe a small indexing/slicing error somewhere?
