### ISSUE TITLE
A question about 2D ROI extracting.

### ISSUE THREAD

**Issue by Williamongh** [Radiomics/pyradiomics#519]
Hi everyone! Thanks for sharing!

Here is my question:
My CT images' thickness is different (1mm - 5mm). So I want to extract 2D features while ignoring the noise because of the difference in thickness.

How should I handle this? Will it work using code as below? :
```
resampledPixelSpacing: [1, 1, 0]
force2D: true
```

Thank you!
Best regards.

**Comment by JoostJM** [comment]
@Williamongh, yes. The effect of this is that it will resample in x and y to 1 mm, while retaining the spacing in z (whatever the size is). the force2D flag ensures PyRadiomics only uses offsets that move in-plane (i.e. not between slices). 

Be aware though that the LoG filter ignores this and applies the filter in 3D (kernel is defined in mm). This only applies to the filter itself. Features extracted from the LoG image are then again only calculated in 2D.

**Comment by Williamongh** [comment]
Thank you @JoostJM .
>Be aware though that the LoG filter ignores this and applies the filter in 3D (kernel is defined in mm). This only applies to the filter itself. Features extracted from the LoG image are then again only calculated in 2D.

It seems like features extracted from the LoG image are still affected by the thickness. 
Would it be better if I apply this setting only for LoG, while other settings stay unchanged? :
```
LoG: 
  # my images' thickness is between [1mm - 5mm], a resampled spacing 2.5mm may be appropriate.
  resampledPixelSpacing: [2.5, 2.5, 2.5]
  sigma: [1.0, 2.0, 3.0, 4.0, 5.0]  
```
